async (page) => {
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto('http://127.0.0.1:4173/');
  await page.getByText('人物流年',{exact:true}).click();
  await page.getByRole('searchbox',{name:'篩選時間軸人物'}).fill('张辽');
  await page.waitForFunction(()=>document.querySelectorAll('.timeline-row').length===1);
  const initial=await page.locator('.row-track').evaluate(e=>e.getBoundingClientRect().width);
  await page.getByRole('button',{name:'放大時間軸',exact:true}).click();
  const enlarged=await page.locator('.row-track').evaluate(e=>e.getBoundingClientRect().width);
  if(enlarged<=initial)throw new Error('Zoom did not increase scale');
  await page.locator('.person-name').click();
  await page.locator('.person-portrait img').waitFor();
  await page.waitForFunction(()=>{const i=document.querySelector('.person-portrait img');return i&&i.complete&&i.naturalWidth>0;});
  const portrait=await page.locator('.person-portrait').evaluate(e=>{
    const i=e.querySelector('img'),c=e.querySelector('figcaption');return {width:i.width,height:i.height,loaded:i.complete&&i.naturalWidth===120,captionBelow:c.getBoundingClientRect().top>=i.getBoundingClientRect().bottom};
  });
  if(!portrait.loaded||!portrait.captionBelow||portrait.width!==120||portrait.height!==120)throw new Error('Portrait dimensions, loading or caption placement failed');
  await page.keyboard.press('Escape');
  await page.getByRole('searchbox',{name:'篩選時間軸人物'}).fill('');
  const visible=await page.locator('.timeline-row').count();if(visible>45)throw new Error('Virtual rendering exceeded visible-row budget');
  await page.getByRole('spinbutton',{name:'跳轉年份，184 至 280'}).fill('280');
  await page.getByRole('button',{name:'前往',exact:true}).click();
  if(!(await page.locator('#playTitle').innerText()).includes('280'))throw new Error('280 endpoint missing');
  await page.getByRole('button',{name:'關閉年份事件',exact:true}).click();
  await page.getByRole('button',{name:'全程',exact:true}).click();
  await page.locator('.event-cluster').first().click();
  if(!await page.locator('#mask').isVisible())throw new Error('Event cluster did not open');
  await page.keyboard.press('Escape');
  await page.getByText('郡縣總表',{exact:true}).click();
  await page.locator('#tblQ').fill('南阳');
  if(await page.locator('#tbl tbody tr').count()<1)throw new Error('Simplified table search failed');
  await page.getByText('疆域地圖',{exact:true}).click();
  if(await page.locator('#ovSvg circle').count()<50)throw new Error('Map regression');
  await page.locator('#q').fill('诸葛亮');
  if(!(await page.locator('#results').innerText()).includes('諸葛亮'))throw new Error('Simplified global search failed');
  await page.locator('#results .res').first().click();
  await page.locator('#mask').waitFor({state:'visible'});
  if(!(await page.locator('#modal h2').innerText()).includes('諸葛亮'))throw new Error('Global person jump failed');
  await page.keyboard.press('Escape');
  await page.setViewportSize({width:390,height:844});
  const mobile=await page.evaluate(()=>({body:document.body.scrollWidth,viewport:innerWidth,table:document.getElementById('timelineViewport').clientWidth}));
  if(mobile.body>mobile.viewport+1)throw new Error('Page overflow on mobile');
  await page.screenshot({path:'output/playwright/mobile.png'});
  await page.setViewportSize({width:1440,height:960});
  await page.getByRole('searchbox',{name:'篩選時間軸人物'}).fill('张辽');
  await page.getByRole('button',{name:'全程',exact:true}).click();
  await page.screenshot({path:'output/playwright/timeline-final.png'});
  await page.locator('.person-name').click();
  await page.screenshot({path:'output/playwright/person-final.png'});
  if(errors.length)throw new Error(errors.join('\n'));
  return {errors,portrait,mountedRows:visible,mobile,checks:'zoom, endpoints, filtering, search, source modal, map, table, portrait, virtualization, responsive layout passed'};
}
